### ISSUE TITLE
Use Composition Architectural Pattern to enable Photo Site Drivers (!!)

### ISSUE THREAD

**Issue by hopeseekr** [woodsandwalker/Faker-Image#2]
Hi!

I want to create drivers for the following sites:

* https://placekitten.com/
* https://thecatapi.com/
* esp https://cataas.com/

But this would entail a lot of work. Please consider adding me as a direct developer on this project so that most of the credit stays with you.

Thanks!

**Comment by woodsandwalker** [comment]
We have no plans to integrate with any other placeholder image providers or allow users to choose between multiple options.
